name: Normalize Repos

on: 
  schedule:
  - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        cd normalize_repos
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Export token to env and run normalize script
      run: |
        export GITHUB_TOKEN=${{ secrets.ADMIN_GITHUB_TOKEN }}
        python3 normalize_repos.py
        